book.json
This is same functionality as described in https://github.com/PX4/Devguide/pull/137
=> Add toobar buttons to ease simple page editing and reporting bugs

LANGS.md, kr/README.md, kr/SUMMARY.md, kr/camera_protocol.md, kr/general_telemetry.md, kr/gimbal_protocol.md, kr/mission_protocol.md, kr/offboard_control.md, kr/parameter_protocol.md, kr/protocol.md, kr/routing.md, kr/serialization.md
I added kr folder for Korean doc.
Please check it out.
=> Add Korean

en/SUMMARY.md, en/uavcan-interaction.md
See https://github.com/mavlink/mavlink/pull/733#issuecomment-307552557.
I attempted to send this change request via the GitBook infrastructure, but could not do so because I don't have editing access to the book.
Paging @mhkabir @LorenzMeier @eyeam3.
=> Chapter on UAVCAN interaction

en/README.md, kr/README.md
This adds slack badge to front of guide. Would like to add "releases" badge too, but that will be second phase.
=> Add slack badge

LICENSE
https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt
This is consistent with all other Dronecode doc sets.
=> Add licence text for CC BY-SA 40.

en/README.md, kr/README.md
- add info for discussion, license, bugs and issues
Todo
=> Improve introduction with high level engagement info

en/protocol/parameter.md
Param value error / Semd typo
Update of visual diagram for better explanation
=> Fix typos - Update diagram

en/SUMMARY.md, en/getting_started/ros.md
Recently I had to generate mavlink headers to work with ROS. I didn't find any documentation on the topic. This is a first draft to document what I discovered.
=> Mavlink headers generation for ROS

en/SUMMARY.md, kr/SUMMARY.md
=> Update Dronecode SDK sidebar link

en/guide/mavlink_2.md
New content for MAVLink 2 doc. Fell out of work looking into the MAVLink 2 serialisation format.
=> Add info about compatibility/incompatibility flags

en/guide/xml_schema.md
Updates as a result of https://github.com/ArduPilot/pymavlink/pull/211
@amilcarlucas , this is only first step - I don't want to update the howto doc until we have some real examples and answers to a few questions inline
=> Update schema documentation with new param info

en/file_formats/README.md, en/services/parameter.md
This is WIP. Initially just updated the sequence docs and operations. [Rendered version here](https://hamishwillee.gitbooks.io/ham_mavdevguide/content/v/paramupdate/en/services/parameter.html)
=> Update parameter microservice doc

en/services/camera.md
Addresses issues raised in https://github.com/mavlink/qgroundcontrol/issues/7324
Rendered version of changes can be seen [here](https://hamishwillee.gitbooks.io/ham_mavdevguide/content/v/imagecapture/en/services/camera.html#still-image-capture)
=> CameraProtocol: Sequences for Image Capture

en/guide/mavlink_version.md
=> Corrected grammar mistake

en/services/camera.md
This attempts to spell out even more clearly how video streaming works
YOu can check this out rendered here: https://mavlink.io/v/hamishwillee-streaming/en/services/camera.html#video_streaming
=> Camera: Attempt to make it even more clear how streaming works

en/services/parameter.md
Fixes https://github.com/mavlink/mavlink/issues/1181
=> Parameters: Clarify how parameter lists maintained

en/services/parameter.md
Fixes additional feedback from https://github.com/mavlink/mavlink-devguide/pull/204#issuecomment-532072214
@olliw42 I did not necessarily agree with every suggestion, but I have attempted to clarify appropriately. Thanks for your feedback.
Please sanity check
=> Parameter: Minor tidy

en/SUMMARY.md, en/services/README.md, en/services/tunnel.md
Fixes https://github.com/mavlink/mavlink/issues/1225
The TUNNEL is more a message than a service. I created this to capture some of the discussion around its use and allocation of the ids.
=> Document Tunnel protocol

en/services/mission.md
#157 included "unapproved" additions for partial upload/downlod. This removes those changes (merged last night). 
The remainder of that PR was a good tidy of the doc.
=> mission.md: Remove accidentally added partial upload/download

en/services/camera.md
The text was OK but didn't make it clear up in the image capture section of the need for the camera to update the image count. I also thought this section important enough to have a heading. 
@MatejFranceskin OK?
=> Update text to re-request missing image

en/mavgen_c/README.md
Updated some words on the 'Using C MAVLink Libraries (mavgen)' document.
- Complete a sentence.
=> Corrected some words on README.md

en/services/opendroneid.md
Signed-off-by: Soren Friis <soren.friis@intel.com>
=> Smaller clarifications for the Open Drone ID documentation

en/guide/routing.md
"target_system_ofs" is repeated. changed the second one according to context, don't %100 sure if it is true as I am new to this.
=> fixed typo

en/contributing/contributing.md
General guidance, as discussed in https://github.com/mavlink/mavlink/issues/1098
@podhrmic Seem reasonable?
=> contributing: New generator

en/file_formats/README.md
Parameter5 should be a "LATITUDE" and Parameter6 should be a "LONGITUDE".
=> Fixed a wrong order of the header format

en/services/gimbal_v2.md
This adds a section on what is required to implement the gimbal v2 device interface.
=> gimbal_v2: add howto gimbal v2 device

en/services/gimbal_v2.md
Follow on from https://github.com/mavlink/mavlink-devguide/pull/279
=> Subedit gimbal device implementation how to

en/services/gimbal_v2.md
Clarifies https://github.com/mavlink/mavlink-devguide/pull/282#issuecomment-706005053
=> Gimbal - gimbal can't always get sisid from autopilot

en/services/mission.md
Fixes https://github.com/mavlink/mavlink/issues/1507 
@ValentineStone would appreciate your review
=> Clarify use of frames in missions

en/services/ftp.md
=> ftp: improve CRC description

en/services/ftp.md
See https://github.com/mavlink/mavlink-devguide/pull/296/files#r539735059
=> FTP: Clarify the English on CRC32

en/guide/xml_schema.md
Adds docs on on the instance field, introduced in https://github.com/mavlink/mavlink/pull/1489
=> Schema: add instance field

en/about/overview.md, en/guide/serialization.md
Depends on: https://github.com/ArduPilot/pymavlink/pull/481
=> Fix CRC specification.

en/README.md, en/getting_started/use_libraries.md
Updating with info from rust team https://github.com/mavlink/rust-mavlink/issues/82
=> Rust links to docs, tests

en/services/battery.md
Follows on from https://github.com/mavlink/mavlink/pull/1595
Self merging. FYI @julianoes
=> Add info about smart battery compids and type

book.json, en/guide/xml_schema.md
Add to XML schema doc. Missing info, as noted in https://github.com/mavlink/mavlink/pull/1698 .
@olliw42 Merging, but feel free to note issues as a post process.
=> Document invalid fields

en/services/component_information.md
Provides some documentation for https://github.com/mavlink/mavlink/pull/1729.
=> component_information: add COMP_METADATA_TYPE_ACTUATORS

en/about/support.md
Otherwise this is likely wrong.
=> about: link to calendar for call time

en/messages/_html/ASLUAV.html, en/messages/_html/all.html, en/messages/_html/ardupilotmega.html, en/messages/_html/common.html, en/messages/_html/development.html, en/messages/_html/icarous.html, en/messages/_html/matrixpilot.html, en/messages/_html/minimal.html, en/messages/_html/paparazzi.html, en/messages/_html/standard.html, en/messages/_html/uAvionix.html, en/messages/_html/ualberta.html
The automatic docs build process is not working. This is a manual update to get us in sync until I can sort out the problem.
=> Update messages to latest versions

en/guide/define_xml_element.md, en/guide/xml_schema.md
Fixes https://github.com/ArduPilot/pymavlink/issues/615
The requirement was added to validator in https://github.com/ArduPilot/pymavlink/pull/630
=> Document that every message must have at least one field

en/services/opendroneid.md
Signed-off-by: Soren Friis <soren.friis@intel.com>
=> Update OpenDroneID documentation

en/getting_started/generate_libraries.md, en/getting_started/installation.md, en/getting_started/ros.md, en/mavgen_c/README.md, en/mavgen_python/README.md
When I looked at MAVLink the first few times, I found it hard to understand some of the basic instructions. For example, what does it mean to "install mavlink"? Install the generator? The generated library? The XML definitions? All of it? :smile: 
I tried to make some of these instructions more concise and meaningful.
=> Some clarifications especially for the getting started guide

en/services/component_information.md
Follows https://github.com/mavlink/mavlink/pull/1934
=> component metadata: add translation docs

en/README.md, en/getting_started/generate_libraries.md, en/getting_started/installation.md, en/mavgen_c/README.md
Various changes related to https://github.com/mavlink/mavlink/pull/1977 and additionally a few nitpicks while reading through it.
Check commits when reviewing.
=> Pass over Python, C, cmake instructions

en/services/command.md
@julianoes Attempted to capture when/why you use command int - would appreciate a sanity check.
Also one question below.
=> Command protocol updates for command_int vs command long

en/mavgen_python/README.md
Drops support for Python 2.7 and tidies doc
=> Tidy mavlinkpython guide

en/guide/define_xml_element.md
I don't want to keep ranges updated in two places. So this cross links to all.xml for "more information".
=> Update define_xml_element.md - add link to all.xml with more ranges

en/mavgen_c/README.md
Adds a note stating what to do if you get hard faults on other hardware, and pointing to problematic boards.
This comes out of discussion here: https://github.com/mavlink/mavlink-devguide/pull/426#issuecomment-1620904619
FYI @julianoes @peterbarker
=> What do do about unaligned access

en/guide/define_xml_element.md
=> Update define_xml_element.md. Wrong link

en/SUMMARY.md, en/mavgen_python/examples.md
Fixes https://github.com/mavlink/mavlink.io/pull/2
=> Fix Pymvalink typos

en/about/implementations.md
Hi guys, I'm happy to announce the release of brand new Mavlink gcs - LOGOS.
I would be really appreciated if you include it in your list.
https://aerologos.by/
=> introduce LOGOS GCS

en/services/README.md
=> Fix microservices link to timesync

en/guide/routing.md
=> Update routing.md - update mavlink router link

en/guide/define_xml_element.md, en/guide/xml_schema.md
=> Add multiplier info to docs

assets/services/illuminators/illuminator.py, assets/services/illuminators/test_illuminator.py, en/services/README.md, en/services/illuminator.md
adding illuminator protocol microservice document and test suite
=> Skydio add illuminator protocol

en/SUMMARY.md, en/guide/README.md, en/guide/packet_loss.md
We're in discussion about the flaws in this mechanism. Time to document them.
=> Add docs on packet loss calculations

en/SUMMARY.md, en/services/README.md, en/services/illuminator.md
Adds to sidebar, and consistency subedit.
Follows on from #535
=> Illuminator tidy

.github/workflows/docs_deploy.yml, .vitepress/config.mjs
Because that is offsetting the some of the search paths
=> Build doesn't use branches

en/SUMMARY.md, en/services/standard_modes.md
Fix up the protocol docs following the protocol moving out of WIP https://github.com/mavlink/mavlink/pull/2161
=> Standard modes protocol update and removal of WIP
