book.json, en/README.md, en/protocol.md
This fixes broken links. 
It also adds these two plugins to **book.json** that can be used to allow link checking on Windows.
The two plugins are disabled by default (see the preceding "-")
```
"-stub-out-blocks@git+https://github.com/hamishwillee/gitbook-plugin-stub-out-blocks.git",
"-validate-links"
```
* The **validate-links** plugin generates a list of broken links when you run `gitbook serve`. It is disabled by default because it causes the build to fail on gitbook.com or linux builds. 
* The **stub-out-blocks** plugin provides an empty implementation for mermaid tags. This is useful on Windows, where mermaid has lots of installation issues. If you disable mermaid and enable this then you can do build testing of everything except mermaid on Windows.
So, to use this during testing (on …
=> Fix broken links. Add link checker for dev

en/SUMMARY.md, en/arm_authorization.md
I was not able to build the docs to see the output, it hangs forever:
```
[zehortigoza@josouza-MOBL mavlink-devguide]$ gitbook build
info: parsing multilingual book, with 2 languages
info: 17 plugins are installed
info: 16 explicitly listed
info: loading plugin "youtube"... OK
info: loading plugin "richquotes"... OK
info: loading plugin "anchors"... OK
info: loading plugin "page-toc-button"... OK
info: loading plugin "mermaid"... OK
info: loading plugin "toolbar"... OK
info: loading plugin "language-picker"... OK
info: loading plugin "custom-favicon"... OK
info: loading plugin "validate-links"... OK
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK …
```
=> Add arm authorization flow

en/serialization.md
This adds content from http://qgroundcontrol.org/mavlink/crc_extra_calculation to the Serialisation topic, in response to #26.
Alternative was to add this as a sub-page of serialisation. Decided to embed as there probably isn't too much more to say about serialisation (right?)
Open question - what happens in MAVLink2 extended fields - are they factored in reordering or are they separate?
=> Add Field Reordering and CRC Extra Calculation to Serialisation topic

en/SUMMARY.md, kr/SUMMARY.md, kr/protocol/camera_def.md
The sidebar was getting too large. This is attempt to better group content
- Protocols listed together under the Protocol Overview
- MAVLink 2 put under "MAVLink Version"
Current version can be previewed [here](https://hamishwillee.gitbooks.io/ham_mavdevguide/content/v/e7da88c73c86057d0a2080bfb72ae61f2380306a/en/protocol/overview.html)
=> Restructure MAVLink devguide to make it more navigable

en/README.md
According to https://github.com/ArduPilot/pymavlink/issues/151#issuecomment-367160812 only the C generated source is fully ported to MAVLink 2. Java is in progress and the rest have nothing. This note is supposed to make that clarification.
I'd also like to add this same caution at the end of the https://mavlink.io/en/getting_started/generate_source.html#generating-source-files topic.
This is waiting for (hopefully) some issue numbers I can add for tracking MAVLink 2 support for the other languages.  - FYI @magicrub
=> Clarify that MAVLink2 only supported for C

en/README.md, en/getting_started/generate_source.md, kr/README.md, kr/getting_started/generate_source.md
This addresses https://github.com/mavlink/mavlink-devguide/pull/45#issuecomment-367252349 comment that C++11 *only* supports MAVLink 2. 
To make this clear and scalable as more language support is added I have separated the supported languages by protocol. I have also updated getting started to make it clear that if the programming language doesn't support the selected version then generation will fail. 
I'll merge this immediately.
=> Clarify MAV version to programming lang version (C++11)

en/README.md, en/SUMMARY.md, en/getting_started/README.md, en/getting_started/examples_scripts.md, en/getting_started/generate_source.md, en/getting_started/installation.md, en/getting_started/ros.md, en/getting_started/use_source.md, en/messages/README.md
This PR attempts to address issues raised by  @amilcarlucas in https://github.com/mavlink/mavlink/commit/d9f5c427726651760ccfc9e0df12a5ca03c12eec#commitcomment-28749814
Updated - not doing this for now:
* In https://mavlink.io/en/getting_started/use_source.html there should be a link to https://github.com/tridge/ardupilot/blob/mavlink2-wip/libraries/GCS_MAVLink/GCS_Signing.cpp
=> [WIP] Improve structure and better reference generating source files

en/messages/README.md
There was a case where a dialect had a single message and included the standard dialect (which includes common). The resulting `MAVLINK_MESSAGE_CRCS` only contained one entry. And only having one entry causes the CRC extras search to fail, even though we were actually trying to transmit the one message who's CRC was still there.
Upshot double-include is not properly supported, at least for all edge cases. This note aims to make that clear that there are potential problems, without having to debug them.
=> Clarify deep nesting of message files is not tested

en/getting_started/examples_scripts.md, en/getting_started/installation.md
This addresses #55 by adding https://github.com/mavlink/c_uart_interface_example to the docs. It also adds https://github.com/mavlink/mavlink/tree/master/examples/linux
@LorenzMeier I decided to put this in the existing Scripts/Examples folder under "Getting Started". I think this is the right place for it because you'd want to discover this pretty early. 
Arguably it could be at the same level, immediately below Getting Started. I would put it there if we had more examples, and a number of examples that were beyond "getting started". Let me know if you think that is better.
=> Add c_uart example to docs

en/SUMMARY.md, en/about/ecosystem.md
Ported from mavlink.org and updated (dead links removed or updated).
@LorenzMeier Any more projects, GCS, Autopilots you can think of that need adding?
Note: I will create Korean placeholder doc (based on English version) after this is approved.
=> Add MAVLink Ecosystem information

en/README.md
Added the clarification about the input, as provided by Lorenz (ie both inputs and output of generator toolchain are MIT licensed). The generator toolchain itself is LPGL.
=> Clarify that message definitions are also MIT licensed

en/about/faq.md, en/guide/serialization.md
This essentially targets the topic towards mavlink generator creators (ie not so much for users). 
It makes certain sections more readable - in particular the explanation of CRC extra and the message reordering.
There are a few outstanding questions:
1. Why does MAVLink 2 NOT reorder fields for new messages/extension fields - for MAVLink 1 this was considered very important for data alignment. Seems inconsistent.
1. CRC_EXTRA appears not to apply to extension messages. Why? See https://github.com/ArduPilot/pymavlink/issues/196
1. How does packet truncation work? I understand that biggest array is moved to end, and if end is zero filled it gets truncated. ... but then am confused about this being moved, since everything else indicates that fields aren't reordered in mavlink 2. Please …
=> Further tidy/clarification of serialization section

en/protocol/ftp.md
For FTP this tidies up some of the existing definition and adds all but one of the missing definition.
The missing operation is BurstMode. It needs more info - see https://github.com/mavlink/mavlink-devguide/issues/98
=> Add missing operations to ftp protocol

en/guide/mavlink_version.md
- Clarifies the supported methods for getting version
- Adds note about version 0.9 (user feedback that the existence of this code was confusing)
- Does NOT attempt to explain how we actually iterate the versions.
=> [WIP] Clarify version support

book.json
This doesn't make a huge difference in most cases, but it reduces common.xml from about 1Mb to around 700K.
=> Add html/javascript/whatever minifier

en/SUMMARY.md, en/guide/message_signing.md, en/mavgen_python/README.md, en/protocol/heartbeat.md
Added pymavlink docs, and general information about system connections in Pymavlink.
Rendered version can be found [here](https://hamishwillee.gitbooks.io/ham_mavdevguide/content/v/pymavlink/en/mavgen_python/)
A few open questions/issues:
=> Pymavlink docs

en/about/overview.md, en/guide/mavlink_2.md, en/guide/serialization.md
This attempts to start moving away from a focus of "MAVLink 1 with MAVLink 2 additions" to find better places for some of the information. It is a bit experimental, but no worse in terms of content than previous version. May change in future. Self merging.
=> Move MAVLink 2 content around

en/SUMMARY.md, en/services/obstacle_avoidance.md, en/services/trajectory.md
This adds draft docs for the MAVLink protocol used for PX4 Obstacle avoidance. Rendered version can be seen [here](https://mavlink.io/v/obstacle_service/en/services/trajectory.html)
@mrivi Can you please review this and see comments inline. I'd like to start with the generic doc on protocol so I can link to it from PX4 information. 
> **NOTE** 7 Nov 2018 - This has been updated to be "generic" (not specific to obstacle avoidance)
=> Path Planning protocol docs

en/guide/routing.md
I'm now fairly sure that the rules for routing do/should not change for signed packets. There are too many other things that would break if they did. 
This makes the rules clear (and fixes #984).
=> Clarify signing routing rules

en/mavgen_c/README.md
The current C-library docs assume that there is a top level **mavlink.h** file that you can `#include` to import all headers in the generated library. 
```c
#include <mavlink/mavlink.h>
```
This does not appear to exist, and I do not think it could because there would inevitably be name clashes in any reimplementation of a message.
1. Is the above correct?
2. So the right way to do this is to include just the header file for your dialect. Any other dialects included in the definition are automatically imported. Correct?
3. The old text said "*If headers for multiple dialects and/or versions are installed, then ...*".
- I have fixed the case for multipole *independent* dialogs - you just include the header file for each
- But what do you mean by "versions"? If you mean multiple versions of …
=> [WIP] Clarify how to add C headers to a project

en/mavgen_c/README.md
Added clear advice that you should only include your top level dialect(s), but not header files generated for sub dialects.
The reason is that C only allows enums to be defined once - not extended. So the top level #defines all sub dialect enums/message ids. If you include in the wrong order you will lose the parent dialect definitions.
=> MavgenC: Not include headers of included dialects

en/guide/routing.md
Clarify that a message that cannot be process by a system (e.g. due to CRC error from message not being supported, or being signed and the system does not have the key) should still be routed appropriately. This ensures that a message will get to all eligible recipients.
Note that this was inferred by the rules, but is now explicitly stated.
=> Routing: Messages must be routed even if not processed

en/services/parameter.md
This clarification removes ambiguity about when the parameter index and count may be assumed to be invariant (arises from https://github.com/PX4/Firmware/issues/11017). Essentially they must be relied upon to be constant during the "read all parameters" operation, because otherwise you can't safely get missing params.
The docs make it clear that the values "should not" be relied on outside of this operation, and state that people must use param id if it is known.
=> Parameter index invariant during readall params

en/services/mission.md
Improve document structure. Capture deltas for ArduPilot implementation. 
WIP while I make docs "more complete". Need to cover:
- ArduPilot differences
- Atomic/robust updates
- Partial uploads/reads
=> [WIP] MissionService: Structure doc. Add ArduPilot/PX4 deltas from spec

en/services/mission.md
This adds an ArduPilot compatibility section 
- makes it clear how ArduPilot differs from the spec
- tries to make it clear how ArduPilot behaves irrespective of the spec in order to work out where the spec might be deficient (ie we should specify more).
- At the end someone implementing a GCS or API to talk to ArduPilot should be able to get this to work from the docs.
=> [WIP] MissionProtocol:ArduPilot compatibility

en/services/parameter.md
This describes my interpretation of the code around GCS parameter caching. 
Essentially the first item sent on request for the list of parameters is the hash of all parameters with a special index. The GCS gets this index, compares the hash, and if it is the same can start using the cached set of parameters without having to wait. If it is not the same the GCS can collect the remaining parameters as usual. 
Notes:
- I think this is not part of the "official" protocol which is why it is under the PX4 Implementation section (correct me if I'm wrong).
- it would be more efficient if the remaining parameters were not send if the hash matched, but the protocol has no mechanism for stopping the rest being sent. Please confirm what I wrote is accurate.
=> ParameterProtocol: Describe param cache mechanism

en/guide/xml_schema.md
MAV_CMDs are a special enum, and are the only place you should use param and the other command metadata. So have separated this out into own section to make that more clear.
=> XMLSchema: Separate out MAV_CMD

en/guide/define_xml_element.md, en/guide/xml_schema.md
The reserved and default attributes for params went into the schema this week. This PR documents the intent.
Note that the change is in and can be used, but I hope for https://github.com/ArduPilot/pymavlink/pull/269 to go in to make sure that generated source code docs reflect this.
FYI @amilcarlucas
=> Add reserved/default param info

en/guide/define_xml_element.md, en/guide/xml_schema.md
Primarily adding this to clarify that all words in a param label should be capitalised.
=> Add info about param attributes

en/getting_started/generate_libraries.md
Fixes #178
The previous version implied that the supported languages table defined what libraries can be _generated_ by mavgen, when actually it documents what versions of the protocol are supported for each programming language. 
This was confusing because the supported languages says C++11 supports MAVLink 1 (which it does, via the MAVLink 2 library) and a user was interpreting this to mean that the generator can create a MAVLink 1-only  library.
The fix explicitly states what libraries can be generated by mavgen, and links to the table only for other programming languages.
=> Clarify what libs can be generated by mavgen

en/guide/routing.md
FYI @olliw42 This clarifies that if a message cannot be handled locally it should be treated as a broadcast message and forwarded appropriately. 
The previous text said that it should be forwarded according to the routing rules. The subtle difference is that if the message is not understood then the system _cannot_ determine the target component/system id. So forwarding according to the intention of the message is not possible.
=> Locally unprocessable messages should be treated as broadcast

en/mavgen_c/README.md
The doc previously said that you can include headers from multiple independent dialects. However this is not possible because it would result in a redefinition of  `MAVLINK_MESSAGE_CRCS`. The result would be that some messages would not be readable (which ones depends on order of inclusion). There are likely other implications too. 
The change says that you should only include the header file for one dialect in your project, and that if you need to support multiple dialects you should create a parent dialect to include it (this works because the message crc for a dialect includes the crcs for all included definitions)
Thanks to @olliw42 for reporting this one in https://github.com/mavlink/mavlink/issues/1123
=> Remove multi-header inclusion

en/services/heartbeat.md
This updates the heartbeat/connection protocol docs. 
- Previously the docs were all about how the heartbeat is used for determining if a system has connected/disconnected from other systems. This is somewhat true.
- More precisely/generically the heartbeat is used for advertising whether a system is active/inactive *on the network*, and this might also tell you if a vehicle is connected/disconnected from another system.
Subtle difference, but it allows us to differentiate between two systems that happen to be active on the network and are "connected" in that they know about each other and will use that info to route packets, vs systems that are connected in the way that a GCS and vehicle are for command and control
Anyway, this change makes the differentiation. As part of this it points …
=> HEARTBEAT - Differentiate active vs connected

en/README.md, en/getting_started/generate_libraries.md
At time of writing there are build errors reported when you run generator. These will be fixed in https://github.com/ArduPilot/pymavlink/pull/318 - but they don't prevent usage of ouputs.
=> Update docs to indicate CS has mavlink 2 support

en/README.md
In the past months i've developed a pure-Go Mavlink library (https://github.com/gswly/gomavlib), that is finally stable enough to be used in production systems.
In particular, the library:
* is part of the software of a rover used during maintenance of state-owned Italian dams and underground power lines
* supports transparently Mavlink 1.0, 2.0 and all the 2.0 features (zero byte truncation, signing, extra fields)
* is written in standard, clear Go (https://goreportcard.com/report/github.com/gswly/gomavlib)
* ships with a huge test suite and CI (https://travis-ci.org/gswly/gomavlib)
* has a complete and standard documentation (https://godoc.org/github.com/gswly/gomavlib)
* has examples (https://github.com/gswly/gomavlib/tree/master/example)
* has a very permissive license (MIT)
Since:
* …
=> Add Go library

en/contributing/contributing.md
Fixes #185 
There was some confusion about where to draw the line for using RFC or PRs. As discussed in devcall we want to use RFCs for microservices, because a lot more discussion is required to explain the complexity of state machines and potentially multiple messages. PRs are generally fine for standalone messages or sets of messages without the additional complexity of a state machine.
This rewords the contribution categories around complexity, making it clear that PRs are for most simple changes. There may be some edge cases, but this more closely reflects how everyone works.
@TSC21 - can you please confirm that this is sufficiently unambiguous?
=> Contributing: Clearly define RFC vs PR process

en/services/parameter.md
Fixes https://github.com/mavlink/mavlink/issues/1139 . 
Specifically it clarifies that:
- GCS should timeout on non-response to PARAM_REQUEST_LIST
- All addressed components should respond with parameters if they have them, and otherwise ignore the request. 
- This therefore explains what components should do if they have no params.
@DonLakeFlyer Note that this is slightly more generic than what QGC does. You specifically notify the user if the autopilot does not respond with params. I don't comment on that - as long as the recipient does not send params if it doesn't have any and the GCS times out, it can notify or not for any component as it likes. 
@DonLakeFlyer @olliw42 - WOuld appreciate your sanity check. You can preview this here: …
=> Param protocol: PARAM_REQUEST_LIST timeout and zero params

en/guide/serialization.md
Hi, recently i stumbled upon an incompatibility issue between libraries, related to the empty-byte truncation feature:
https://github.com/gswly/gomavlib/pull/2
* gomavlib was built by following the developer guide, which says to truncate all empty-bytes at the end of a payload, even if the payload becomes null
* the reference c library implements the empty-byte feature in a different way, as it always keeps at least a byte in the payload
A change in the c library is not possible, as it would influence all the Mavlink ecosystem; instead, i propose to add this behavior to the documentation, in order to clarify the situation.
=> serialization: clarify empty-byte truncation in case of empty payloads

en/services/ftp.md
@julianoes @MatejFranceskin This improves explanation of ListDirectory operation/sequence based on feedback from @olliw42 [here](https://github.com/mavlink/mavlink/issues/1208#issuecomment-522931496)
I don't want to merge until we know that PX4 matches this. The specific points that might differ are:
1. This uses drone returning EOF to indicate that offset is outside directory listing and complete operation.
2. The format of the returned entry information. 
Rendered version is [here](https://hamishwillee.gitbooks.io/ham_mavdevguide/content/v/ftp_filelist/en/services/ftp.html#list_directory)
Can you confirm you're OK to merge?
=> FTP service: Clarify ListDirectory

en/services/camera.md
Fixes https://github.com/mavlink/mavlink/issues/1218
=> camera.md: GCS must support mavftp and http for def file download

en/services/ftp.md
Fixes https://github.com/mavlink/mavlink/issues/1209
Note, I just made error "NotFound" so it can cover both Files and Folders (Dirs). HOw do people feel about naming? FileFolderNotFound, ErrorNotFound, PathNotFound are all options
=> FTP: Add File/Folder not found NAK

en/services/ftp.md
This fixes modifies minimum value for `size` of data from 1 to 0. This is an error, because there are commands that can have no data - e.g. `TerminateSession`, `ResetSessions`.
@WickedShell, @julianoes FYI. I think this makes sense.
=> FTP: Typo - size of data in payload can be zero

en/SUMMARY.md, en/services/README.md, en/services/smart_battery.md
This is minimal docs for the smart battery "service". I'm aware this is not a protocol in the same way as most of the others, ie. in that it has no message sequence etc. It is however useful to group the messages.
@julianoes I'm hoping the services protocol you're reviewing for this weeks mavlink meeting can do this in a more automated way - ie for a basic grouping of messages in a service we can just document this at the top level of a message definition and automatically build this kind of doc if we want.
=> Add smart battery service docs

en/services/parameter.md
Fixes https://github.com/mavlink/mavlink-devguide/issues/186
So in normal flow GCS first reads all params, after which it has a list of params, a range of ids and a list of ids that it has names for. From the range and ids the GCS has, it knows what ids are missing, so it can request these params individually by id.
The protocol assumes that you can always read a param value by name - ie [that they are invariant](https://mavlink.io/en/services/parameter.html#parameters-assumed-invariant). It also assumes thatd that the ids are can be relied upon at least for the time while you are doing your initial reads.
However neither of these things are necessarily true. 
What this does is explain what happens if you try read a param that is not defined by name or ID. Essentially this is not properly …
=> Parameters: Clarify read invalid param

en/services/parameter.md
@LorenzMeier Noted in https://github.com/mavlink/mavlink-devguide/pull/209#issuecomment-532546499 that the parameter set must be invariant. 
This was inferred but not clearly stated. Now it says:
> The protocol *requires* that the parameter set does not change during normal operation/after parameters have been read.
=> Params: Make clear parameter set is invariant

en/services/command.md
This is basic docs to follow on from https://github.com/mavlink/mavlink/pull/1253 - essentially to show a sequence of a progress update. That is the last sequence shown, and looks as below: 
Julian, this is not intended to a be a full and beautiful document. I just wanted to achieve these things:
1. Should list the main messages/enums and link to them
2. Should show both the main sending messages.
3. Should identify where/why both messages are problematic. 
It should be correct but not complete. Ie I'm not planning on expanding this out much further right now.
=> Command Protocol: Initial basic docs

en/services/camera.md
Follows on from https://github.com/mavlink/qgroundcontrol/pull/7964
@dogmaphobic @olliw42 I don't think we should say more than this in the MAVLink spec. The QGC developer guide might additionally say what the camera widget does with such information.
Reasonable?
=> Camera battery status publishing

en/SUMMARY.md, en/services/opendroneid.md
Please provide guidance on how exactly the documentation should be added?
Is it enough to add just this one file or should similar files be created for the other language variants?
Is the amount of documentation sufficient?
=> Add documentation for Open Drone ID messages

en/README.md
As per the patch at https://github.com/ArduPilot/pymavlink/commit/281d940e9a4ad760dffa58a06bed2cbd5f80d9e0, mavgen can now generate MAVLink 2.0 messages for Javascript
=> Mavlink Guide: Add Mavlink 2 for Javascript gen

en/mavgen_c/README.md
Fixes https://github.com/mavlink/mavlink/issues/1330
Well, technically it just documents the dependency. We should fix the headers, but that's a bigger problem.
@peterbarker - seem reasonable?
=> mavlink_system must be declared in global scope

en/services/camera_def.md
The param CAM_MODE is actually always needed, so we should mention it here.
=> camera_def: add note about CAM_MODE param

en/services/mission.md
This updates the sections for partial upload/download of missions. PX4 does not implement this so what I have done is inferred sensible operation from the normal upload/download and reviewed ArduPilot implementation. 
Would be good if I can get some confirmation that the proposal is sensible even though it might not perfectly match what ArduPilot does @WickedShell, @auturgy . Rendered version is here: https://hamishwillee.gitbooks.io/ham_mavdevguide/content/v/mission_ap/en/services/mission.html#upload_partial
What I have said is 
1. Partial upload is JUST LIKE full upload except it is triggered by `MISSION_WRITE_PARTIAL_LIST` instead of a `MISSION_COUNT`
- I have stated that this has to be robust like a full update (ie update succeeds completely or fails and original state restored). Is …
=> MissionProtocol: Partial upload/download

en/getting_started/generate_libraries.md, en/getting_started/installation.md
Docs were not quite right for Python 3. With Python 2 now deprecated this changes docs to be Python 3-first.
=> installation: Update to be correct for Python 3 and prioritse that

en/services/camera.md
Describe the procedure on how to detect and request lost CAMERA_IMAGE_CAPTURED messages.
Updates camera protocol based on https://github.com/mavlink/mavlink/pull/1385
=> Added section about requesting lost image captured messages

en/mavgen_c/README.md
Updated some words on the 'Using C MAVLink Libraries (mavgen)' document.
"parse_statemavlink_status_t" should be changed to "mavlink_status_t.parse_state"
=> Corrected some words on README.md - 2

en/services/command.md
it might also be "specify co-ordinate frame of positional parameters."(omitted "the"). I am not sure.
=> typo in command.md

en/SUMMARY.md
=> SUMMARY: Further clarify that Open drone id is WIP protocol

en/services/mission.md
Documents deprecation of the MISSION_REQUEST and MISSION_INT messages as per https://github.com/mavlink/mavlink/pull/1389
@julianoes I think this is a good update, but would appreciate a sanity check.
=> Mission: Deprecate non INT message usage

en/services/gimbal_v2.md
This contains a couple of changes that are suggested to the gimbal v2 protocol:
- Add GIMBAL_MANAGER_CONFIGURE message to select sysid/compid in primary
and secondary control.
- Add GIMBAL_MANAGER_SET_MANUAL_CONTROL ~and
GIMBAL_DEVICE_SET_MANUAL_CONTROL~ for direct manual control.
- Remove nudge and override flags and all that complexity.
- Remove the deconfliction part, now that we have the configure message.
Goes with https://github.com/mavlink/mavlink/pull/1466.
@hamishwillee I'm not happy with the new MANUAL_CONTROL messages and considering to add a flag called UNITLESS to the TILTPAN message which means the speed is set by GIMBAL_MANAGER and/or GIMBAL_DEVICE according to settings which would then be the same as the manual control message.
=> gimbal_v2: add manual_control, configure messages

en/services/mission.md
Essentially you set MAV_FRAME_MISSION (meaning "frame not applicable"). A well designed message should only use and INT for these fields. If a float must be sent in them then it will need to be scaled in some way, and that should be recorded in the mav_cmd itself.
@auturgy FYI, this came up in a discussion I had about what MAV_FRAME_MISSION should be used for.
=> Mission - clarify how mission param 5/6 used if NOT positional data

en/services/ftp.md
This should describe what CRC32 is used and how it differes from the ISO 3309 standard.
Related to https://github.com/mavlink/mavlink/issues/1219.
Closes #258.
=> ftp: notes on CRC32 standard

en/services/image_transmission.md
Fixes https://github.com/mavlink/mavlink-devguide/issues/297
This corrects and improves the docs, which are clearly wrong (I think they reflect an early design). There are two things I am not certain of.
1. Image width, height - units are pixels right?
2. What is the format of the DATA_TRANSMISSION_HANDSHAKE to stop the sequence and to ACK stopping the sequence? I have indicated that both of these are a message with all zero values. Is that OK - the old described method isn't valid.
The reason I am not sure of the stop sequence is that I can't see QGC or PX4Flow implementing this.
@LorenzMeier @Marxlp @DonLakeFlyer Can one of you advise/review
=> Correct image transmission documentation

en/SUMMARY.md, en/services/README.md, en/services/high_latency.md
@DonLakeFlyer This is draft docs for the High latency API following our discussion [here](https://github.com/mavlink/qgroundcontrol/pull/9101#issuecomment-704524299). 
Can you please let me know if these assumptions are correct (yes, no, maybe, don't know)
1. Vehicle pretty much _only_ emits HIGH_LATENCY2 and it acts as both heartbeat and as essential telemetry. 
2. Vehicle doesn't emit other messages.
3. Vehicle only emits HIGH_LATENCY2  message when commanded by MAV_CMD_CONTROL_HIGH_LATENCY 
4. QGC sends MAV_CMD_CONTROL_HIGH_LATENCY when an HL link becomes the primary. 
5. The implication of 4 is that the connection is unlike a normal LL connection where you start communicating on the same link by sending heartbeats and you know that the connection has fallen out when the heartbeat …
=> High Latency Protocol 

en/about/faq.md
Added this as attempt to answer slack query "what is your release process". My understanding of the process is that we try to only make changes that are backward compatible so that we don't have to do any sort of official notifications to avoid "breaking" people.
What this says though is that we can do it if we want, but we'll email the mailing list to notify. 
@auturgy seem reasonable?
Also added direct suggestion to use MAVLink 2 over MAVLink 2 - seems like a good idea!
=> Clarify use MAVLink2 and Release process

en/services/gimbal_v2.md
I should move this test to https://github.com/Auterion/mavlink-testing-suite/ but for now that's where it lives.
=> gimbal_v2: add link to gimbal device test

en/SUMMARY.md, en/services/README.md, en/services/component_information.md, en/services/ftp.md
Initial docs for component information base on current behaviour as discussed in https://github.com/mavlink/mavlink/issues/1346 (note, it is WIP).
This services is still marked WIP and there are still discussions around:
- where files should be hosted 
- integrating with uavcan and other busses
@bkueng @julianoes @LorenzMeier @auturgy @DonLakeFlyer Can you guys please sanity check?
=> Component Information Service docs

en/services/gimbal_v2.md
This should make it more discoverable.
Suggested by @LorenzMeier.
=> gimbal_v2: add info box for device tester

en/services/heartbeat.md
Historically component ids were used for determining component type. However about a year ago it was decided that the type of a component should come from its heartbeat, and that any component id can be used. This has some benefits because in theory now a component id is just used for routing. 
Note though, even though component ids can't be relied on to infer type, it still makes sense to use type-specific ids for a default value. Reason being that this reduces the chance of clashes if you add a new gimbal, say to your system. [of course you still need a way to set component and system ids for a system if the default is already used - e.g if you had two GPS].
This change captures those implications.
Note, I don't love it. Mostly because there is SO much legacy code that still assumes the …
=> Clarify use of MAV_TYPE and what compid to use

LANGS.md
Replaces #271
The Korean translation from crowdin is only 1% while the old version is more complete. However the old version is getting progressively out of date - so it is "deceptive".
This basically means that we lose the translations but at least we start from a fresh slate. I have however kept the old translations for reference, for now.
=> Make crowdin translation of Korean display

en/SUMMARY.md, en/guide/README.md, en/guide/crc.md, en/services/ftp.md, en/services/parameter.md
@julianoes As discussed.
At the moment is refers to CRCs rather than CRC32, because I wanted to check what you think about the "need" to talk about the CRC used in the checksum here: https://mavlink.io/en/guide/serialization.html#checksum
if you think this should just be ignored, then I would probably rename the heading CRC32.
=> Add mavlink crc topic

en/README.md, en/getting_started/use_libraries.md
Hey folks
I'd like to add the [fastMavlink](https://github.com/olliw42/fastmavlink) C library to the docs. 
This is strongly motivated by the discussion in https://github.com/mavlink/mavlink-devguide/pull/190, which essentially says "everything gets to go in" (with "everything" of course subject to common sense). It looks to me that the situation for the fastMavlink library is not different to e.g. that for the Go library discussed there.
Also, I do have various pieces of the fastMavlink code base in use since 2 years (it all started with https://github.com/mavlink/mavlink/pull/1127) in my STorM32 project, which evolved as [mavlink light](https://github.com/olliw42/mavlink/tree/light) to finally becoming fastMavlink. I am using the fastMavlink library since several months in my STorM32 …
=> Add fastMavlink C library

en/README.md
This separates the project owned generators from the external generators and puts them in alphabetic order. The reason for this is that it makes it easier to highlight what is supported by the project and what is not.
=> Separate project and non-project generators

en/guide/serialization.md
https://mavlink.io/en/guide/serialization.html
Current span of  payload for MAVLink v2 is described as `10 to (n+10)`, and I believe this is a typo.
For other multi-byte fields like v2 msg_id the byte indices in the left column are inclusive - both byte 7 and byte 9 are part of msg_id. So a payload of one byte should be from byte 10 to byte 10 inclusive. The formula to get one-byte payload then is actually `10 to (n+9)` because n = 1. This might feel a bit strange to programmers used to inclusive-exclusive array boundaries but is correct in this context.
A different explanation is that the byte (n+10) is actually the first byte of the checksum, not the last byte of payload. With current documentation it is unclear which part it belongs to.
This is also true for v1 packet.
=> Fix payload byte indices in serialization.md

en/getting_started/installation.md
Python 2 is pretty much end of life. 
This simplifies the instructions by removing the interleaved Python2 instructions. It also adds info on installing the xml validation tools and linter on Ubuntu. It does not do this for Windows (it should, but I don't see that as urgent).
=> Installation move to Python3 only

en/services/high_latency.md
Questions came up as a result of a new implementation of latency protocol (MAVProxy) that were unanswered/unclear in current doc. 
What this says is.
- `HEARTBEAT` is not sent over low latency links.
- `HIGHLATENCY2` is not a heartbeat.
- `Broadcast messages from network are not sent over the high latency link.
The HEARTBEAT is what builds routing tables. What this implies is that everything on the the network with get HIGHLATENCY2 info but only the connected GCS will be able to command the vehicle. If we want other things to be able to do so, then we would have to update the routing docs (and routers) to say that HIGHLATENCY2 should also be used to build routing. 
As an aside, there is a possibility that HIGHLATENCY2 should be updated to include a base mode to allow it to be used on …
=> Clarify HIGH_LATENCY2 and HEARTBEAT

en/contributing/contributing.md
From https://github.com/mavlink/mavlink/issues/1617#issuecomment-853420162 it wasn't clear what tests that a user has to run to contribute to mavgen.
To address this I added a "How to Contribute to Mavgen" section, which starts by mentioning that changes to existing code are first tested in CI - ie you don't need to explicitly run tests. This then continues as before with general requirements for adding a new programming language support.
NOTE, I wish we had instructions on how you could run the tests locally - I can't get that to work. 
@davidbuzz FYI - seem OK to you?
=> Clarify how to contribute to mavgen

en/services/high_latency.md
This PR addresses a few issues I've had whilst implementing the High Latency service on ArduPilot.
For reference, the "high latency" link I've been working with is an Inmarsat SBD, which allows ~60 bytes per second, with a 10-30 second latency.
They are:
A) Allowable messages. Only the bare minimum messages should be sent for basic control and status updates.
-The GCS should only send COMMAND_LONG and HEARTBEAT messages to the autopilot. Requesting params, waypoints, etc will clag up a high latency link fairly quickly.
-Likewise, the autopilot should only send the HIGH_LATENCY2 and any COMMAND_ACK messages to the GCS on the high latency link.
B) Changing between low and high latency links
-Both autopilot and GCS should be able to cope with both low and high latency links being used …
=> Update High Latency service details

en/services/heartbeat.md
The messages say this, but not the guide. The important point is that the easiest way to detect the autopilot is to check `HEARTBEAT.autopilot` is not `MAV_AUTOPILOT_INVALID`
Fixes https://github.com/mavlink/mavlink/issues/1682
=> Clarify that components set HEARTBEAT.autopilot to MAV_AUTOPILOT_INVALID

en/services/camera_def.md
Updates file compression in camera definition guide to match the information in the messages (common.xml). 
Note that at time of writing no one sending camera definition files is sending them compressed, so this change has no impact on existing systems.
Fixes #1681
=> Camera def - use XZ compression

en/SUMMARY.md, en/services/README.md, en/services/payload.md, en/services/payload_control.md
There are a whole bunch of MAVLink commands for affecting payloads. This attempts to categorise and document them. 
Kicked off by adoption of `MAV_CMD_DO_SET_ACTUATOR` into PX4.
=> Add doc on payload control options

en/services/opendroneid.md
The ASTM F3411 Specification for Remote ID and Tracking has
been updated to version 1.1 and the FAA has published the
final rule for remote ID in the United States.
Change the related MAVLink message documentation to be compliant.
Signed-off-by: Soren Friis <soren.friis@intel.com>
=> Update OpenDroneID documentation to be compliant with ASTM spec v1.1

en/SUMMARY.md, en/services/README.md, en/services/manual_control.md
- covers basic axis-mappings
- includes extensions added in https://github.com/mavlink/mavlink/pull/1674
- covers some reasoning from https://github.com/mavlink/mavlink/issues/1694 and https://github.com/ArduPilot/ardupilot/issues/9808
=> Document manual control service

en/services/camera_def.md
Adds new [Common camera parameters](https://mavlink.io/en/services/camera_def.html#common-parameters) to allow GCS to create custom UI location for [selecting video streams](https://github.com/mavlink/mavlink/issues/1678#issuecomment-906731177), and a number of other things.
Fixes https://github.com/mavlink/mavlink/issues/1306
=> Add additional common camera parameters

en/SUMMARY.md, en/services/README.md, en/services/events.md
There have been recent questions about how to solve certain problems recently where the answer is "the events protocol".
To ease answering these questions I have created a placeholder WIP doc on the events interface.
It is very "thin" - mostly it explains the reason for the interface and points to the proposal for more information. I also list the affected messages/enums and link to the implementation PRs.
FYI @bkueng I'm kind of expecting you to update this once we have "released" the interface.
FYI only @auturgy - easy way to find the events info if needed in future.
=> Add events interface WIP docs

en/guide/xml_schema.md
Clarify the invalid values as discussed in https://github.com/mavlink/mavlink-devguide/commit/31080c0cc478508fdc289d4c3d070877c38357c1#commitcomment-59508846
@olliw42 FYI. We now need to update the cases in common to match this.
=> xml_scheme - clarify the invalid values again

en/services/command.md
@julianoes @peterbarker
This updates long running commands as discussed in this thread: https://github.com/mavlink/mavlink-devguide/pull/405#issuecomment-965905186
Specifically, different long running commands in parallel are allowed, but the same long running command is not. If you want to update an in-progress command it has to be cancelled first. It is implied but not stated that polling is not supported.
An implication of the fact that commands must be cancelled would be that if you had a takeoff long running command you can't just send a new command to change the height as you might now. You must send a cancel, which the flight stack can choose to ignore if it wants.
=> Long running commands can be executed in parallel

en/mavgen_c/README.md
https://github.com/mavlink/mavlink/issues/1764 reported build warnings, and asked if we should care.
This PR adds a note that they can be ignored (and how). It also reorders the How to use section slightly so upgrading from MAVLink 1 is now after the "Adding libraries" - most people will already have upgraded.
=> Using C library - add info on build warnings

en/mavgen_c/README.md
This provides information that the packed structures are properly aligned - i.e. why you can ignore the build warnings.
The information came from here: https://github.com/mavlink/mavlink/issues/1770#issuecomment-1007035187
Peter made it clear this was an "in my understanding" and not "gospel truth". I have included it anyway because it seems logical based on my reading, and if it is not correct, I am sure some expert will explain why in short order.
=> Explain mavlink packed values are properly aligned

en/mavgen_c/example_c_udp.md
This updates the UDP docs to MAVLink 2, to match https://github.com/mavlink/mavlink/pull/1778
Essentially `SYS_STATUS` now has extension fields so this example ONLY works with MAVLink 1. I could have rejected the change and left everything the same, but I think now MAVLink 2 is the "expectation".
=> example_c_udp: update to MAVLink 2

en/services/ftp.md
As discussed in [dev call](https://github.com/mavlink/mavlink/wiki/20220216-Dev-Meeting), good to make it clear that we didn't invent FTP, and that MAVFTP is a close copy of the original protocol.
=> FTP - clarify MAVFTP maps closely to FTP

en/services/parameter.md
Essentially we have two parameter protocols, that pretty much differ only in that PX4 uses byte-wise encoding and ArduPilot uses C-style encoding (there are other differences, but most of these are not incompatible - more like extensions).
The suggestion by @auturgy here: https://github.com/mavlink/mavlink/pull/1769#issuecomment-1038479154 was that we simply use the protocol bits `MAV_PROTOCOL_CAPABILITY_PARAM_UNION` and `MAV_PROTOCOL_CAPABILITY_PARAM_FLOAT` to differentiate these. These can then also be used for discovery of the protocol. 
I like this because it more accurately reflects the actual history - early inconsistency in the implementations, and further, it might actually have been the intent of these protocol bits originally. 
Do not merge until …
=> Parameter protocol updates for encoding method

en/README.md
Updated the MAVLink Project Generators/Languages Table for java support for MAVLink 2 and signing
In the MAVLink Project Generators/Languages table, at https://mavlink.io/en/#mavlink-project-generatorslanguages, for Java the check/tick is not there for MAVLink 2 and Signing columns, but mavgen can create MAVLink 2 libraries for Java
The MAVLink 2 and Signing columns should be checked for Java and in Notes column we can state to use dronefleet, since dronefleet is fully implemented
Resolving Issue: https://github.com/mavlink/mavlink-devguide/issues/457
=> Doc Update: changes for Java mavgen

en/SUMMARY.md, en/services/README.md, en/services/component_information.md
This updates the component metadata guide material.
It's just the high level stuff. When translation stuff is in place we should update that too. Ditto the support for "dynamic updates".
@bkueng Can you sanity check this ? ALso how is the translation /dynamic support  "coming along"
=> Update docs to COMPONENT_METADATA (from _INFORMATION)

en/services/landing_target.md
ArduPilot support for LANDING_TARGET mavlink2 position extension field now. https://github.com/ArduPilot/ardupilot/pull/21329
=> update ArduPilot LANDING_TARGET support

en/README.md
Add [mavlink-kotlin](https://github.com/urbanmatrix/mavlink-kotlin), a new Kotlin/JVM MAVLink library to the External Generators/Languages section.
=> Add mavlink-kotlin to External Generators section

en/guide/serialization.md
MAVLink is little endian over the wire, and libraries are set up to run on little endian architectures by default. Added to the Serialization topic. Probably also need info on the C topic, since there are a whole bunch of defines.
This was news to me - I knew we were little endian over the wire, but somehow assumed that setup for current architecture was achieve by magic.
FYI @auturgy
=> Add note about endianness in serialisation

en/guide/wireshark.md
See https://www.wireshark.org/docs/wsug_html_chunked/ChPluginFolders.html.
Should we keep the old one as well?
=> wireshark: update plugin directory for unix

en/services/camera.md
@julianoes This adds docs about the camera tracking API that just moved out of WIP. I probably should have done this first.
My understanding is that if tracking is supported you start and stop it using the respective commands. While tracking the camera emits image and/or geo information - this can then be used to provide a position for a gimbal to track. You can set the streaming rates of those messages using the set message interval command. Is that about right?
Some assumptions I want to test:
1. The image status message provides info about the tracking image. This is information can be used, along with camera FOV to work out the target location to track. Is that right? Is anything else needed?
2. The geo status message is the actual target - so if you have a camera (or intermediate …
=> Add docs on camera tracking to camera protocol

en/SUMMARY.md, en/mavgen_python/README.md, en/mavgen_python/_examples/setratecommandspecific.py, en/mavgen_python/examples.md, en/mavgen_python/howto_requestmessages.md, en/mavgen_python/message_signing.md
This splits out an Examples section, message signing, how to stream/receive messages sections from the main doc.
The stream/recieve message doc is updated to use the interval message.
This is nowhere near enough work, but I'm stumped because I don't have the time to do it right. What I'd like to do is start with a tutorial/quickstart that shows a guided path using mavutil including connecting, sending message, receiving message, sending command, perhaps handling command. Everything else would then follow and be split out.
At the moment it is daunting, while actually most people would not need all that much.
First thing would probably be a doc on commands and command handling.
=> Pymavlink updates/restructure

en/services/command.md
There's a new result you should return for this case - added in https://github.com/mavlink/mavlink/pull/2001
This adds docs.
=> Command protocol - add info about unsupported frames

en/services/gimbal_v2.md
This should make it clearer how the magic numbers 2..6 are used instead of MAVLink component IDs to signal that the gimbal device is the same component as the gimbal manager.
Does that make sense @Davidsastresas?
=> gimbal_v2: How to address non-MAVLink gimbals

en/services/opendroneid.md
@friissoren There is a discussion in https://github.com/PX4/PX4-Autopilot/pull/21647/files#r1251208151 about the requirement for the arm status to go to the GCS.
I understand that it needs to go to the vehicle, which should not arm if the remoteid is not armed. 
I think this is saying that if the remote id is lost while flying, this should count as a malfunction and be reported in the LOCATION message status - right? (i.e. from: During flight, if the arm status indicates a failure, similar action must be taken as for a lack of `HEARTBEAT` messages.)
What is the requirement for a GCS? The way this read the GCS should be notified so it can track errors and prevent takeoff. A GCS can't prevent takeoff - it can send commands to takeoff or not send commands, but it is the autopilot that …
=> opendroneid - arming status clarification

en/services/ftp.md
It turns out the docs don't reflect the implementations out in the wild.
The size field of a burst transfer is used to set the size per burst, so 1..239 rather than specifiying the overall file size to burst read.
As discussed in https://github.com/mavlink/mavlink/issues/2052.
=> ftp: clarify size during burst

en/services/battery.md
SMART_BATTERY_INFO was renamed to BATTERY_INFO and updated to match the corresponding CAN message in https://github.com/mavlink/mavlink/pull/2070.
This updates the battery protocol docs in line with that change.
=> battery.md - de smart battery-ify the protocol

en/services/gimbal_v2.md
Following the discussion here: https://github.com/mavlink/mavlink/issues/2093#issuecomment-1993144508
@julianoes @hamishwillee let me know if it looks good to you. Thanks!
=> gimbal_v2.md: Add clarification about gimbal yaw frame

en/services/camera.md
This updates the camera protocol to note that it is the MAV_TYPE that is used to identify a camera. Using component IDs to identify components is discouraged, though it is widely used.
I have kept the recommendation to use the allocated component IDs. 
FYI @DonLakeFlyer @auturgy @julianoes
=> Camera discovery

en/SUMMARY.md
Matching dialect was removed some time ago.
=> Remove autoquad from the sidebar

en/services/camera.md
Work related to https://github.com/mavlink/mavlink/pull/2024
This documents the presence of the `id` parameter in the image command. I've tried to make it clear how addressing works both before and after, and in the command protocol and missions.
@julianoes @rmackay9 @Davidsastresas  A couple of things popped up:
1. MAVLink cameras send a `HEARTBEAT` with the camera type, which tells GCS that it should query for CAMERA_INFORMATION using [MAV_CMD_REQUEST_MESSAGE](https://mavlink.io/en/messages/common.html#MAV_CMD_REQUEST_MESSAGE). However an autopilot or onboard computer has its own component ID and type so what should trigger GCS to know it should query the onboard computer?
The obvious answer is that a GCS could choose NOT to wait for heartbeats, but instead fire off …
=> Camera protocol - update with info about camera addressing and missions

en/services/gimbal_v2.md
This updates the protocol to state that gimbal managers are discovered by checking all components individually (replacing the bit that said that the request is broadcast).
We hope to modify this to be a protocol bit check in https://github.com/mavlink/mavlink/pull/2144 , but getting this accurate here "for now".
FYI @julianoes
=> GCS asks all components for gimbal manager info

en/services/camera_def.md
This is just reflecting what's implemented in QGC and MAVSDK.
Also see:
- https://github.com/mavlink/MAVSDK/blob/v2.12/src/mavsdk/plugins/camera/camera_definition.cpp#L368-L413
- https://github.com/mavlink/qgroundcontrol/blob/be1e2d46c95812d3ad700bdc4807eca95829be6b/src/Camera/VehicleCameraControl.cc#L968-L1014
=> camera_def: add parameter ranges

en/services/gimbal_v2.md, en/services/heartbeat.md
This updates gimbal protocol discovery to require using the bit, as described in https://github.com/mavlink/mavlink/pull/2144.
I also took the time to
- simplify the description of mavlink vs non-mavlink gimbals. It is a lot better now.
- update the heartbeat protocol with component information basic. 
Note, PX4 and ArduPilot should set the bit. FYI @rmackay9
PX4 work for this in https://github.com/PX4/PX4-Autopilot/pull/23692/files
=> Gimbal discovery using protocol bit

.vitepress/theme/style.css
The fixes I did to make a wider theme are hacky, and prevented search bar being selected manually (though you can do Ctrl+K). This allows selection of the Ctrl+ K text using mouse.
=> Try make the search bar clickable

en/mavgen_c/example_c_udp.md
Fixes #579
Updated the broken link for the MAVLink UDP Example and changed the file name in the example to match the actual file in the repository.
=> Fix broken link in MAVLink UDP example

en/services/tunnel.md
This removes the concept of reserving payload types for a tunnel - a vendor still gets an allocated block, but if they want a new type they have to come to us.
The main reason is that we don't want tunnels, so doing it this way forces vendors to explain the need, every time. With a reserved value they could in theory live with the reserved name and not come back and discuss. 
Also it is a hassle to no real benefit. 
I have chosen not to undo the STORM reserved items.
This fell out of https://github.com/mavlink/mavlink/pull/2213
@auturgy @julianoes
=> Tunnel - reserving payload types

en/SUMMARY.md, en/services/index.md, en/services/trajectory.md
This deprecates the Path planning interface, reflecting its removal from all flight stacks. 
Removed from the sidebar, but still findable by search.
=> Update trajectory.md - path planning intrface deprecated

en/guide/define_xml_element.md, en/guide/xml_schema.md
We've just finished purging `display="bitmask"` from fields, and making sure that the enum attribute `bitmask="true"` is set on the corresponding enums. This updates the documentation to make it clear which you should use.
Not sure if we're ready to purge `display="bitmask"` from the XSD yet.
=> Add information about the bitmask attribute for enums

en/services/mavlink_id_assignment.md
This cleans up the mavlink id assignment in line with discussions around component ids and mapping to type.
I.e. make clear you can use the MAV_COMPONENT, and it might help avoid clashes, but don't rely on it for determining what type the component is.
=> mavlink_id_assignment.md - clean up

en/getting_started/installation.md
This pull request makes a minor update to the installation instructions for the MAVLink toolchain, specifically correcting the path to the requirements file.
* Updated the `pip install` command in `en/getting_started/installation.md` to use the correct path: `mavlink/pymavlink/requirements.txt` instead of `pymavlink/requirements.txt`.
=> Update installation.md To Make Directions More Clear
